@url=http://localhost:3000

POST {{url}}/usuarios/registro
Content-Type: application/json

{
  "nombre": "jese rodriguez",
  "email": "jesee@gmail.com",
  "password": "Tutifrutti007"
}
### login
# @name login
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "jesee@gmail.com",
  "password": "Tutifrutti007"
}

###
@token = {{login.response.body.token}}

###
GET {{url}}/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT {{url}}/usuarios/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Jose Argento",
  "password": "Tutifrutti007"
}

###
DELETE {{url}}/usuarios/8
Authorization: Bearer {{token}}